#!/bin/bash
BC_FILE="$1"

T_SUPPORT=3
T_CONFIDENCE=65
SHOULD_OPTIMIZE=false
if [ ! -z "$2" ]
then
	if [ ! -z "$3" ]
	then
		T_SUPPORT="$2"
		T_CONFIDENCE="$3"
	else
		SHOULD_OPTIMIZE="$2"
	fi	
fi

if [ ! -z "$4" ]
then
	SHOULD_OPTIMIZE="$4"
fi

opt -print-callgraph $1 1>/dev/null 2>temp.callgraph

java -Xms128m -Xmx128m  Main $T_SUPPORT $T_CONFIDENCE $SHOULD_OPTIMIZE < temp.callgraph 2>/dev/null

rm temp.callgraph 
